/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/je_bae_ted/ec_je_bae_ted/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][2] = {
    {{0, 0, 6, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{1, 0, 0, 17}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
