/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_dolice/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][17] = {
    {{1, 0, 0, 7}, {0, 0, 10, 7}, {0, 1, 18, 7}, {0, 2, 26, 7}, {0, 3, 34, 7}, {0, 4, 42, 7}, {0, 5, 50, 7}, {0, 6, 58, 7}, {0, 7, 82, 7}, {0, 8, 90, 7}, {0, 9, 98, 7}, {0, 10, 106, 7}, {0, 11, 114, 7}, {0, 12, 122, 7}, {0, 13, 130, 7}, {0, 14, 138, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 0, 7}, {1, 1, 10, 11}, {1, 2, 22, 7}, {1, 3, 30, 7}, {1, 4, 38, 7}, {1, 5, 46, 7}, {1, 6, 54, 7}, {1, 7, 78, 7}, {1, 8, 86, 7}, {1, 9, 94, 7}, {1, 10, 102, 7}, {1, 11, 110, 7}, {1, 12, 118, 7}, {1, 13, 126, 7}, {1, 14, 134, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 7}, {2, 1, 10, 13}, {2, 2, 24, 7}, {2, 3, 32, 7}, {2, 4, 40, 7}, {2, 5, 48, 7}, {2, 6, 56, 7}, {2, 7, 80, 7}, {2, 8, 88, 7}, {2, 9, 96, 7}, {2, 10, 104, 7}, {2, 11, 112, 7}, {2, 12, 120, 7}, {2, 13, 128, 17}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 1, 10, 17}, {3, 2, 28, 7}, {3, 3, 36, 7}, {3, 4, 44, 7}, {3, 5, 52, 7}, {3, 6, 60, 7}, {3, 7, 76, 7}, {3, 8, 84, 7}, {3, 9, 92, 7}, {3, 10, 100, 7}, {3, 11, 108, 7}, {3, 12, 116, 7}, {3, 13, 124, 13}, {3, 14, 138, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 1, 10, 11}, {4, 3, 34, 11}, {4, 5, 46, 15}, {4, 6, 62, 9}, {4, 8, 76, 21}, {4, 10, 98, 11}, {4, 14, 134, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
