/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_split_60/info.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][16] = {
    {{0, 0, 0, 7}, {0, 1, 8, 7}, {0, 2, 16, 7}, {0, 3, 24, 7}, {0, 4, 32, 7}, {0, 5, 40, 7}, {1, 5, 48, 7}, {5, 0, 66, 7}, {5, 1, 74, 7}, {5, 2, 82, 7}, {5, 3, 90, 7}, {5, 4, 98, 7}, {5, 5, 106, 7}, {5, 6, 114, 7}, {5, 7, 122, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{1, 0, 0, 11}, {1, 1, 12, 7}, {1, 2, 20, 7}, {1, 3, 28, 7}, {1, 4, 36, 7}, {2, 5, 44, 7}, {6, 0, 62, 7}, {6, 1, 70, 7}, {6, 2, 78, 7}, {6, 3, 86, 7}, {6, 4, 94, 7}, {6, 5, 102, 7}, {6, 6, 110, 7}, {6, 7, 118, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 0, 13}, {2, 1, 14, 7}, {2, 2, 22, 7}, {2, 3, 30, 7}, {2, 4, 38, 7}, {3, 5, 46, 7}, {7, 0, 64, 7}, {7, 1, 72, 7}, {7, 2, 80, 7}, {7, 3, 88, 7}, {7, 4, 96, 7}, {7, 5, 104, 7}, {7, 7, 112, 17}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 17}, {3, 1, 18, 7}, {3, 2, 26, 7}, {3, 3, 34, 7}, {3, 4, 42, 7}, {4, 5, 50, 7}, {8, 0, 68, 7}, {8, 1, 76, 7}, {8, 2, 84, 7}, {8, 3, 92, 7}, {8, 4, 100, 7}, {8, 6, 108, 13}, {8, 7, 122, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 0, 0, 11}, {4, 1, 12, 7}, {4, 2, 20, 11}, {4, 3, 32, 15}, {4, 4, 48, 7}, {9, 0, 66, 7}, {9, 1, 74, 15}, {9, 3, 90, 11}, {9, 4, 102, 7}, {9, 6, 110, 7}, {9, 7, 118, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
