/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_minimi40/stagger/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][13] = {
    {{0, 0, 0, 7}, {1, 0, 8, 7}, {2, 0, 16, 7}, {3, 0, 24, 7}, {4, 0, 32, 7}, {5, 0, 40, 7}, {6, 0, 48, 7}, {7, 0, 56, 7}, {8, 0, 64, 7}, {9, 0, 72, 7}, {10, 1, 80, 7}, {10, 0, 88, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{0, 1, 0, 9}, {1, 1, 10, 7}, {2, 1, 18, 7}, {3, 1, 26, 7}, {4, 1, 34, 7}, {5, 1, 42, 7}, {6, 1, 50, 7}, {7, 1, 58, 7}, {8, 1, 66, 7}, {9, 1, 74, 7}, {10, 2, 82, 13}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{0, 2, 0, 13}, {1, 2, 14, 7}, {2, 2, 22, 7}, {3, 2, 30, 7}, {4, 2, 38, 7}, {5, 2, 46, 7}, {6, 2, 54, 7}, {7, 2, 62, 7}, {8, 2, 70, 7}, {9, 2, 78, 9}, {10, 3, 88, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{0, 3, 0, 9}, {1, 3, 10, 7}, {2, 3, 18, 9}, {4, 3, 28, 17}, {6, 3, 46, 21}, {7, 3, 68, 9}, {8, 3, 78, 7}, {9, 3, 86, 9}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
