/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/lilium/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][16] = {
    {{1, 0, 0, 7}, {0, 0, 8, 7}, {0, 2, 16, 7}, {0, 3, 24, 7}, {0, 4, 32, 7}, {1, 5, 40, 7}, {0, 5, 48, 7}, {0, 6, 66, 7}, {0, 7, 74, 7}, {0, 8, 82, 7}, {0, 9, 90, 7}, {0, 10, 98, 7}, {0, 11, 106, 7}, {0, 12, 114, 7}, {0, 13, 122, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 0, 11}, {1, 1, 12, 7}, {1, 2, 20, 7}, {1, 3, 28, 7}, {1, 4, 36, 7}, {2, 5, 44, 7}, {1, 6, 62, 7}, {1, 7, 70, 7}, {1, 8, 78, 7}, {1, 9, 86, 7}, {1, 10, 94, 7}, {1, 11, 102, 7}, {1, 12, 110, 7}, {1, 13, 118, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 13}, {2, 1, 14, 7}, {2, 2, 22, 7}, {2, 3, 30, 7}, {2, 4, 38, 7}, {3, 5, 46, 7}, {2, 6, 64, 7}, {2, 7, 72, 7}, {2, 8, 80, 7}, {2, 9, 88, 7}, {2, 10, 96, 7}, {2, 11, 104, 7}, {2, 13, 112, 17}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 0, 0, 17}, {3, 1, 18, 7}, {3, 2, 26, 7}, {3, 3, 34, 7}, {3, 4, 42, 7}, {4, 5, 50, 7}, {3, 6, 60, 7}, {3, 7, 68, 7}, {3, 8, 76, 7}, {3, 9, 84, 7}, {3, 10, 92, 7}, {3, 11, 100, 7}, {3, 12, 108, 13}, {3, 13, 122, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 1, 14, 7}, {4, 2, 22, 11}, {4, 4, 34, 23}, {4, 7, 60, 23}, {4, 10, 84, 11}, {4, 11, 96, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
