/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_ogr_65/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][19] = {
    {{0, 0, 0, 7}, {0, 1, 8, 7}, {0, 2, 20, 7}, {0, 3, 28, 7}, {0, 4, 36, 7}, {0, 5, 44, 7}, {0, 6, 52, 7}, {0, 7, 60, 7}, {0, 8, 68, 7}, {0, 9, 76, 7}, {0, 10, 84, 7}, {0, 11, 92, 7}, {0, 12, 100, 7}, {0, 13, 108, 7}, {0, 14, 116, 7}, {0, 15, 124, 7}, {0, 16, 132, 7}, {0, 17, 140, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{1, 0, 0, 7}, {1, 1, 8, 7}, {1, 2, 20, 11}, {1, 3, 32, 7}, {1, 4, 40, 7}, {1, 5, 48, 7}, {1, 6, 56, 7}, {1, 7, 64, 7}, {1, 8, 72, 7}, {1, 9, 80, 7}, {1, 10, 88, 7}, {1, 11, 96, 7}, {1, 12, 104, 7}, {1, 13, 112, 7}, {1, 14, 120, 7}, {1, 15, 128, 7}, {1, 16, 134, 7}, {1, 17, 140, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 0, 7}, {2, 1, 8, 7}, {2, 2, 20, 13}, {2, 3, 34, 7}, {2, 4, 42, 7}, {2, 5, 50, 7}, {2, 6, 58, 7}, {2, 7, 66, 7}, {2, 8, 74, 7}, {2, 9, 82, 7}, {2, 10, 90, 7}, {2, 11, 98, 7}, {2, 12, 106, 7}, {2, 13, 114, 7}, {2, 14, 122, 7}, {2, 15, 130, 9}, {2, 17, 140, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 7}, {3, 1, 8, 7}, {3, 2, 20, 9}, {3, 3, 30, 7}, {3, 4, 38, 7}, {3, 5, 46, 7}, {3, 6, 54, 7}, {3, 7, 62, 7}, {3, 8, 70, 7}, {3, 9, 78, 7}, {3, 10, 86, 7}, {3, 11, 94, 7}, {3, 12, 102, 7}, {3, 13, 110, 7}, {3, 14, 118, 13}, {3, 16, 132, 7}, {3, 17, 140, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 0, 0, 7}, {4, 1, 8, 7}, {4, 2, 20, 9}, {4, 3, 30, 9}, {4, 4, 40, 9}, {4, 6, 50, 17}, {4, 8, 68, 9}, {4, 10, 78, 21}, {4, 12, 100, 9}, {4, 13, 110, 9}, {4, 14, 124, 7}, {4, 16, 132, 7}, {4, 17, 140, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
