/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_minimi40/ortho/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][13] = {
    {{0, 0, 0, 7}, {1, 0, 8, 7}, {2, 0, 16, 7}, {3, 0, 24, 7}, {4, 0, 32, 7}, {5, 0, 40, 7}, {6, 0, 48, 7}, {7, 0, 56, 7}, {8, 0, 64, 7}, {9, 0, 72, 7}, {10, 0, 80, 7}, {11, 0, 88, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{0, 1, 0, 7}, {1, 1, 8, 7}, {2, 1, 16, 7}, {3, 1, 24, 7}, {4, 1, 32, 7}, {5, 1, 40, 7}, {6, 1, 48, 7}, {7, 1, 56, 7}, {8, 1, 64, 7}, {9, 1, 72, 7}, {10, 1, 80, 7}, {11, 1, 88, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{0, 2, 0, 7}, {1, 2, 8, 7}, {2, 2, 16, 7}, {3, 2, 24, 7}, {4, 2, 32, 7}, {5, 2, 40, 7}, {6, 2, 48, 7}, {7, 2, 56, 7}, {8, 2, 64, 7}, {9, 2, 72, 7}, {10, 2, 80, 7}, {11, 2, 88, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{0, 3, 0, 7}, {1, 3, 8, 7}, {2, 3, 16, 7}, {3, 3, 24, 7}, {4, 3, 32, 7}, {5, 3, 40, 7}, {6, 3, 48, 7}, {7, 3, 56, 7}, {8, 3, 64, 7}, {9, 3, 72, 7}, {10, 3, 80, 7}, {11, 3, 88, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
