/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/hybrid_hhkb/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][16] = {
    {{0, 15, 0, 7}, {0, 0, 8, 7}, {0, 1, 16, 7}, {0, 2, 24, 7}, {0, 3, 32, 7}, {0, 4, 40, 7}, {0, 5, 48, 7}, {0, 6, 56, 7}, {0, 7, 64, 7}, {0, 8, 72, 7}, {0, 9, 80, 7}, {0, 10, 88, 7}, {0, 11, 96, 7}, {0, 12, 104, 7}, {1, 12, 112, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{1, 15, 0, 11}, {1, 0, 12, 7}, {1, 1, 20, 7}, {1, 2, 28, 7}, {1, 3, 36, 7}, {1, 4, 44, 7}, {1, 5, 52, 7}, {1, 6, 60, 7}, {1, 7, 68, 7}, {1, 8, 76, 7}, {1, 9, 84, 7}, {1, 10, 92, 7}, {1, 11, 100, 7}, {2, 12, 108, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 16, 0, 13}, {2, 0, 14, 7}, {2, 1, 22, 7}, {2, 2, 30, 7}, {2, 3, 38, 7}, {2, 4, 46, 7}, {2, 5, 54, 7}, {2, 6, 62, 7}, {2, 7, 70, 7}, {2, 8, 78, 7}, {2, 9, 86, 7}, {2, 10, 94, 7}, {3, 12, 102, 17}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 17, 0, 17}, {3, 1, 18, 7}, {3, 2, 26, 7}, {3, 3, 34, 7}, {3, 4, 42, 7}, {3, 5, 50, 7}, {3, 6, 58, 7}, {3, 7, 66, 7}, {3, 8, 74, 7}, {3, 9, 82, 7}, {3, 10, 90, 7}, {3, 13, 98, 13}, {3, 14, 112, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 18, 12, 7}, {4, 19, 20, 11}, {4, 20, 32, 47}, {4, 21, 80, 11}, {4, 22, 92, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
