/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_typek_advanced/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][17] = {
    {{1, 0, 6, 7}, {0, 0, 20, 7}, {0, 1, 28, 7}, {0, 2, 36, 7}, {0, 3, 44, 7}, {0, 4, 52, 7}, {0, 5, 60, 7}, {0, 6, 68, 7}, {0, 7, 84, 7}, {0, 8, 92, 7}, {0, 9, 100, 7}, {0, 10, 108, 7}, {0, 11, 116, 7}, {0, 12, 124, 7}, {0, 13, 132, 7}, {0, 14, 140, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 4, 7}, {1, 1, 18, 11}, {1, 2, 30, 7}, {1, 3, 38, 7}, {1, 4, 46, 7}, {1, 5, 54, 7}, {1, 6, 62, 7}, {1, 7, 82, 7}, {1, 8, 90, 7}, {1, 9, 98, 7}, {1, 10, 106, 7}, {1, 11, 114, 7}, {1, 12, 122, 7}, {1, 13, 130, 7}, {1, 14, 138, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 2, 7}, {2, 1, 16, 13}, {2, 2, 30, 7}, {2, 3, 38, 7}, {2, 4, 46, 7}, {2, 5, 54, 7}, {2, 6, 62, 7}, {2, 7, 86, 7}, {2, 8, 94, 7}, {2, 9, 102, 7}, {2, 10, 110, 7}, {2, 11, 118, 7}, {2, 12, 126, 7}, {2, 14, 134, 17}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 0, 0, 7}, {3, 1, 14, 17}, {3, 2, 32, 7}, {3, 3, 40, 7}, {3, 4, 48, 7}, {3, 5, 56, 7}, {3, 6, 64, 7}, {3, 7, 84, 7}, {3, 8, 92, 7}, {3, 9, 100, 7}, {3, 10, 108, 7}, {3, 11, 116, 7}, {3, 12, 124, 7}, {3, 13, 132, 9}, {3, 14, 142, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 1, 14, 11}, {4, 3, 40, 11}, {4, 5, 52, 15}, {4, 6, 68, 7}, {4, 7, 80, 7}, {4, 8, 88, 15}, {4, 10, 104, 11}, {4, 13, 134, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
