/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/des_60/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][16] = {
    {{0, 1, 0, 7}, {1, 1, 8, 7}, {0, 2, 16, 7}, {3, 2, 24, 7}, {0, 4, 32, 7}, {1, 4, 40, 7}, {2, 4, 48, 7}, {0, 6, 56, 7}, {0, 11, 64, 7}, {1, 11, 72, 7}, {2, 11, 80, 7}, {0, 12, 88, 7}, {1, 12, 96, 7}, {2, 12, 104, 7}, {0, 13, 112, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 1, 0, 11}, {3, 1, 12, 7}, {1, 2, 20, 7}, {2, 2, 28, 7}, {3, 4, 36, 7}, {1, 6, 44, 7}, {2, 6, 52, 7}, {0, 9, 60, 7}, {1, 9, 68, 7}, {2, 9, 76, 7}, {3, 11, 84, 7}, {3, 12, 92, 7}, {1, 13, 100, 7}, {2, 13, 108, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{0, 0, 0, 13}, {1, 0, 14, 7}, {2, 0, 22, 7}, {0, 3, 30, 7}, {0, 5, 38, 7}, {0, 7, 46, 7}, {3, 6, 54, 7}, {3, 9, 62, 7}, {0, 10, 70, 7}, {1, 10, 78, 7}, {0, 8, 86, 7}, {0, 14, 94, 7}, {1, 14, 102, 17}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 17}, {1, 3, 18, 7}, {1, 5, 26, 7}, {2, 5, 34, 7}, {3, 5, 42, 7}, {1, 7, 50, 7}, {2, 7, 58, 7}, {2, 10, 66, 7}, {3, 10, 74, 7}, {1, 8, 82, 7}, {2, 8, 90, 7}, {2, 14, 98, 13}, {3, 13, 112, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 3, 12, 7}, {2, 3, 20, 11}, {3, 7, 32, 47}, {3, 8, 80, 11}, {3, 14, 92, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
