/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_frl82/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][21] = {
    {{0, 0, 0, 7}, {0, 1, 8, 7}, {0, 2, 16, 7}, {0, 3, 24, 7}, {0, 4, 32, 7}, {0, 5, 40, 7}, {0, 6, 48, 7}, {0, 7, 56, 7}, {0, 8, 64, 7}, {0, 9, 72, 7}, {0, 10, 80, 7}, {0, 11, 88, 7}, {0, 12, 96, 7}, {0, 13, 104, 7}, {0, 14, 112, 7}, {0, 15, 120, 7}, {0, 16, 130, 7}, {0, 17, 138, 7}, {0, 18, 146, 7}, {1, 18, 154, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{1, 0, 0, 11}, {1, 1, 12, 7}, {1, 2, 20, 7}, {1, 3, 28, 7}, {1, 4, 36, 7}, {1, 5, 44, 7}, {1, 6, 52, 7}, {1, 7, 60, 7}, {1, 8, 68, 7}, {1, 9, 76, 7}, {1, 10, 84, 7}, {1, 11, 92, 7}, {1, 12, 100, 7}, {1, 13, 108, 11}, {1, 14, 120, 7}, {1, 15, 130, 7}, {1, 16, 138, 7}, {1, 17, 146, 7}, {2, 18, 154, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 0, 13}, {2, 1, 14, 7}, {2, 2, 22, 7}, {2, 3, 30, 7}, {2, 4, 38, 7}, {2, 5, 46, 7}, {2, 6, 54, 7}, {2, 7, 62, 7}, {2, 8, 70, 7}, {2, 9, 78, 7}, {2, 10, 86, 7}, {2, 11, 94, 7}, {2, 13, 102, 17}, {2, 14, 120, 7}, {2, 15, 130, 7}, {2, 16, 138, 7}, {2, 17, 146, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 17}, {3, 2, 18, 7}, {3, 3, 26, 7}, {3, 4, 34, 7}, {3, 5, 42, 7}, {3, 6, 50, 7}, {3, 7, 58, 7}, {3, 8, 66, 7}, {3, 9, 74, 7}, {3, 10, 82, 7}, {3, 11, 90, 7}, {3, 12, 98, 13}, {3, 13, 112, 7}, {3, 14, 120, 7}, {3, 15, 130, 7}, {3, 16, 138, 7}, {3, 17, 146, 7}, {3, 18, 154, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 0, 0, 11}, {4, 2, 18, 11}, {4, 6, 30, 55}, {4, 11, 86, 11}, {4, 12, 104, 7}, {4, 13, 112, 7}, {4, 14, 120, 7}, {4, 16, 130, 15}, {4, 17, 146, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
