/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_60xi/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][31] = {
    {{0, 0, 0, 7}, {0, 1, 8, 7}, {0, 2, 16, 7}, {0, 3, 24, 7}, {0, 4, 32, 7}, {0, 5, 40, 7}, {0, 6, 48, 7}, {0, 7, 56, 7}, {0, 8, 64, 7}, {0, 9, 72, 7}, {0, 10, 80, 7}, {0, 11, 88, 7}, {0, 12, 96, 7}, {0, 13, 104, 7}, {0, 14, 112, 7}, {5, 0, 122, 7}, {5, 1, 130, 7}, {5, 2, 138, 7}, {5, 3, 146, 7}, {5, 4, 154, 7}, {5, 5, 162, 7}, {5, 6, 170, 7}, {5, 7, 178, 7}, {5, 8, 186, 7}, {5, 9, 194, 7}, {5, 10, 202, 7}, {5, 11, 210, 7}, {5, 12, 218, 7}, {5, 13, 226, 7}, {5, 14, 234, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{1, 0, 0, 11}, {1, 1, 12, 7}, {1, 2, 20, 7}, {1, 3, 28, 7}, {1, 4, 36, 7}, {1, 5, 44, 7}, {1, 6, 52, 7}, {1, 7, 60, 7}, {1, 8, 68, 7}, {1, 9, 76, 7}, {1, 10, 84, 7}, {1, 11, 92, 7}, {1, 12, 100, 7}, {1, 13, 108, 7}, {1, 14, 114, 7}, {6, 0, 122, 11}, {6, 1, 134, 7}, {6, 2, 142, 7}, {6, 3, 150, 7}, {6, 4, 158, 7}, {6, 5, 166, 7}, {6, 6, 174, 7}, {6, 7, 182, 7}, {6, 8, 190, 7}, {6, 9, 198, 7}, {6, 10, 206, 7}, {6, 11, 214, 7}, {6, 12, 222, 7}, {6, 13, 230, 7}, {6, 14, 236, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 0, 13}, {2, 1, 14, 7}, {2, 2, 22, 7}, {2, 3, 30, 7}, {2, 4, 38, 7}, {2, 5, 46, 7}, {2, 6, 54, 7}, {2, 7, 62, 7}, {2, 8, 70, 7}, {2, 9, 78, 7}, {2, 10, 86, 7}, {2, 11, 94, 7}, {2, 12, 102, 7}, {2, 13, 110, 9}, {7, 0, 122, 13}, {7, 1, 136, 7}, {7, 2, 144, 7}, {7, 3, 152, 7}, {7, 4, 160, 7}, {7, 5, 168, 7}, {7, 6, 176, 7}, {7, 7, 184, 7}, {7, 8, 192, 7}, {7, 9, 200, 7}, {7, 10, 208, 7}, {7, 11, 216, 7}, {7, 12, 224, 7}, {7, 13, 232, 9}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 9}, {3, 1, 10, 7}, {3, 2, 18, 7}, {3, 3, 26, 7}, {3, 4, 34, 7}, {3, 5, 42, 7}, {3, 6, 50, 7}, {3, 7, 58, 7}, {3, 8, 66, 7}, {3, 9, 74, 7}, {3, 10, 82, 7}, {3, 11, 90, 7}, {3, 12, 98, 7}, {3, 13, 106, 7}, {3, 14, 112, 7}, {8, 0, 122, 9}, {8, 1, 132, 7}, {8, 2, 140, 7}, {8, 3, 148, 7}, {8, 4, 156, 7}, {8, 5, 164, 7}, {8, 6, 172, 7}, {8, 7, 180, 7}, {8, 8, 188, 7}, {8, 9, 196, 7}, {8, 10, 204, 7}, {8, 11, 212, 7}, {8, 12, 220, 7}, {8, 13, 228, 7}, {8, 14, 234, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 0, 0, 11}, {4, 1, 12, 7}, {4, 2, 20, 11}, {4, 4, 32, 11}, {4, 6, 44, 19}, {4, 8, 64, 11}, {4, 10, 76, 11}, {4, 11, 88, 11}, {4, 12, 100, 7}, {4, 13, 108, 11}, {9, 0, 122, 11}, {9, 1, 134, 7}, {9, 2, 142, 11}, {9, 4, 154, 11}, {9, 6, 166, 19}, {9, 8, 186, 11}, {9, 10, 198, 11}, {9, 11, 210, 11}, {9, 12, 222, 7}, {9, 13, 230, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
