/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_virgo/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][19] = {
    {{0, 0, 0, 7}, {0, 1, 10, 7}, {0, 2, 18, 7}, {0, 3, 26, 7}, {0, 4, 34, 7}, {0, 5, 44, 7}, {0, 7, 72, 7}, {0, 8, 80, 7}, {0, 9, 88, 7}, {0, 10, 98, 7}, {0, 11, 106, 7}, {0, 12, 114, 7}, {0, 13, 122, 7}, {0, 15, 138, 7}, {0, 16, 146, 7}, {0, 17, 154, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{1, 0, 0, 7}, {1, 1, 8, 7}, {1, 2, 16, 7}, {1, 3, 24, 7}, {1, 4, 32, 7}, {1, 5, 40, 7}, {1, 6, 48, 7}, {1, 7, 72, 7}, {1, 8, 80, 7}, {1, 9, 88, 7}, {1, 10, 96, 7}, {1, 11, 104, 7}, {1, 12, 112, 7}, {1, 13, 120, 7}, {1, 14, 128, 7}, {1, 15, 138, 7}, {1, 16, 146, 7}, {1, 17, 154, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 0, 11}, {2, 1, 12, 7}, {2, 2, 20, 7}, {2, 3, 28, 7}, {2, 4, 36, 7}, {2, 5, 44, 7}, {2, 6, 68, 7}, {2, 7, 76, 7}, {2, 8, 84, 7}, {2, 9, 92, 7}, {2, 10, 100, 7}, {2, 11, 108, 7}, {2, 12, 116, 7}, {2, 13, 124, 7}, {2, 14, 132, 7}, {2, 15, 138, 7}, {2, 16, 146, 7}, {2, 17, 154, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 13}, {3, 1, 14, 7}, {3, 2, 22, 7}, {3, 3, 30, 7}, {3, 4, 38, 7}, {3, 5, 46, 7}, {3, 6, 70, 7}, {3, 7, 78, 7}, {3, 8, 86, 7}, {3, 9, 94, 7}, {3, 10, 102, 7}, {3, 11, 110, 7}, {3, 12, 118, 7}, {3, 13, 126, 9}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 0, 0, 9}, {4, 1, 10, 7}, {4, 2, 18, 7}, {4, 3, 26, 7}, {4, 4, 34, 7}, {4, 5, 42, 7}, {4, 6, 50, 7}, {5, 6, 66, 7}, {4, 7, 74, 7}, {4, 8, 82, 7}, {4, 9, 90, 7}, {4, 10, 98, 7}, {4, 11, 106, 7}, {4, 13, 114, 13}, {4, 14, 128, 7}, {4, 16, 146, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{5, 0, 0, 11}, {5, 2, 20, 9}, {5, 3, 30, 9}, {5, 5, 40, 17}, {5, 7, 66, 21}, {5, 9, 88, 9}, {5, 10, 98, 9}, {5, 13, 116, 11}, {5, 15, 138, 7}, {5, 16, 146, 7}, {5, 17, 154, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
