/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/hybrid_enso_e/1_1_0/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][16] = {
    {{1, 0, 4, 7}, {0, 0, 12, 7}, {0, 1, 20, 7}, {0, 2, 28, 7}, {0, 3, 36, 7}, {0, 4, 44, 7}, {0, 5, 52, 7}, {0, 6, 70, 7}, {0, 7, 78, 7}, {0, 8, 86, 7}, {0, 9, 94, 7}, {0, 10, 102, 7}, {0, 11, 110, 7}, {0, 12, 118, 7}, {0, 13, 126, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 2, 11}, {1, 1, 14, 7}, {1, 2, 22, 7}, {1, 3, 30, 7}, {1, 4, 38, 7}, {1, 5, 46, 7}, {1, 6, 68, 7}, {1, 7, 76, 7}, {1, 8, 84, 7}, {1, 9, 92, 7}, {1, 10, 100, 7}, {1, 11, 108, 7}, {1, 12, 116, 7}, {1, 13, 124, 11}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 13}, {2, 1, 14, 7}, {2, 2, 22, 7}, {2, 3, 30, 7}, {2, 4, 38, 7}, {2, 5, 46, 7}, {2, 6, 72, 7}, {2, 7, 80, 7}, {2, 8, 88, 7}, {2, 9, 96, 7}, {2, 10, 104, 7}, {2, 11, 112, 7}, {2, 13, 120, 17}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 0, 0, 17}, {3, 1, 18, 7}, {3, 2, 26, 7}, {3, 3, 34, 7}, {3, 4, 42, 7}, {3, 5, 50, 7}, {3, 6, 68, 7}, {3, 7, 76, 7}, {3, 8, 84, 7}, {3, 9, 92, 7}, {3, 10, 100, 7}, {3, 11, 108, 7}, {3, 12, 116, 13}, {3, 13, 130, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{4, 1, 14, 7}, {4, 2, 22, 11}, {4, 4, 34, 15}, {4, 5, 50, 7}, {4, 6, 68, 7}, {4, 7, 76, 15}, {4, 9, 92, 11}, {4, 10, 104, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
