/* This file is generated by cipulot_generate_calibration_layouts.py. */
/* Source: /Users/cipulot/qmk/private_qmk_firmware/keyboards/cipulot/ec_23u/keyboard.json */
#pragma once

#include <stdint.h>

#define CALIBRATION_LAYOUT_END 0xFF

typedef struct {
    uint8_t row;
    uint8_t col;
    uint8_t x;
    uint8_t w;
} calibration_layout_key_t;

static const calibration_layout_key_t calibration_print_layout[][5] = {
    {{0, 0, 0, 7}, {0, 1, 8, 7}, {0, 2, 16, 7}, {0, 3, 24, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{1, 0, 0, 7}, {1, 1, 8, 7}, {1, 2, 16, 7}, {1, 3, 24, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 0, 0, 7}, {2, 1, 8, 7}, {2, 2, 16, 7}, {2, 3, 24, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{3, 0, 0, 7}, {3, 1, 8, 7}, {3, 2, 16, 7}, {3, 3, 24, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 4, 0, 7}, {0, 4, 8, 7}, {1, 4, 16, 7}, {3, 4, 24, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
    {{2, 5, 0, 7}, {0, 5, 8, 7}, {1, 5, 16, 7}, {3, 5, 24, 7}, {CALIBRATION_LAYOUT_END, CALIBRATION_LAYOUT_END, 0, 0}},
};
